app:
  name: card-service
  port: 1500

db:
  host: localhost
  port: 3306
  name: devdb
  username: devusr
  password: devpassword
  connection:
    maxopen: 10
    maxidle: 2

whitelist:
  domain: ["http://localhost:3000"]

internal:
  private:
    key: |

  public:
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz/jpo53y5iuKIWZJPScy
      FfWXzwDajbD5lUZvkwoNh3Aan1UjY9sWHjtmgNgLqUjaJ9BPUCioE7CVNUC1XzOM
      L00wPeHG5KDjPDky6sO0tagrFxPBD3WnqlRS9b5XBFCwK2NSquNYnTx4XlStoIRl
      Aykzc45sOhp/SdI4U7lzU0M50Zf4tDaoXE7O8biZQnxBwwD3sPoSVt0oVu7bcRiS
      cFyXigL2YoPKaTLpEjDTR1+01k8zwv92PUHb8mSjuhaRaFMoyoNijRNpHYQgRPs0
      WakQT4R75BaM4UQrn9eBdAX0sNcSXsgB1a3LGTj706c2A19wkAX71uItC8ggcyaI
      JQIDAQAB
      -----END PUBLIC KEY-----